services:

  database:
    image: postgres:17
    container_name: database
    ports:
      - "5432:5432"

    env_file:
      - path: ./db_app.env
        required: true

  app:
    image: openjdk:21
    container_name: app
    working_dir: /apps/batch/codetickets
    command: java -jar codetickets-0.0.1-SNAPSHOT.jar

    volumes:
      - ./target/:/apps/batch/codetickets

    env_file:
      - path: ./app.env
        required: true
